apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-config
  namespace: {{ .Release.Namespace }}
data:
  dashboards.yml: |
{{ include "requiredFile" (list . "files/grafana/dashboards.yml") | indent 4 }}
  datasources.yml: |
{{ include "requiredFile" (list . "files/grafana/datasources.yml") | indent 4 }}
  anthem-intersection.json: |
{{ include "requiredFile" (list . "files/grafana/data/dashboards/anthem-intersection.json") | indent 4 }}
