apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server-rootcert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root-cert: {{ include "requiredFile" (list . "files/secrets/certs/scenescape-ca.pem") | b64enc | quote }}
