apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-scene-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  scenescape-ca.pem: {{ include "requiredFile" (list . "files/secrets/certs/scenescape-ca.pem") | b64enc }}
  controller.auth: {{ include "requiredFile" (list . "files/secrets/controller.auth") | b64enc }}
  secrets.py: {{ include "requiredFile" (list . "files/secrets/django/secrets.py") | b64enc }}
