apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgserver-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  browser.auth: {{ include "requiredFile" (list . "files/secrets/browser.auth") | b64enc }}
  controller.auth: {{ include "requiredFile" (list . "files/secrets/controller.auth") | b64enc }}
  supass: {{ include "requiredFile" (list . "files/secrets/supass") | b64enc }}
  secrets.py: {{ include "requiredFile" (list . "files/secrets/django/secrets.py") | b64enc }}
